In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv")
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5786 entries, 0 to 5785
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   codigo_ocorrencia2              5786 non-null   int64
 1   aeronave_matricula              5785 non-null   object
 2   aeronave_operador_categoria     5777 non-null   object
 3   aeronave_tipo_veiculo           5785 non-null   object
 4   aeronave_fabricante             5781 non-null   object
 5   aeronave_modelo                 5776 non-null   object
 6   aeronave_tipo_icao              5775 non-null   object
 7   aeronave_motor_tipo             5315 non-null   object
 8   aeronave_motor_quantidade       5785 non-null   object
 9   aeronave_pmd                    5785 non-null   float64
 10  aeronave_pmd_categoria          5785 non-null   float64
 11  aeronave_assentos               4721 non-null   float64
 12  aeronave_ano_fabricacao         5000 non-null   float64
 13  aeronave_pais_fabricante        5785 non-null   object
 14  aeronave_pais_registro          5785 non-null   object
 15  aeronave_registro_categoria     5785 non-null   object
 16  aeronave_registro_segmento      5765 non-null   object
 17  aeronave_voo_origem             5782 non-null   object
 18  aeronave_voo_destino            5783 non-null   object
 19  aeronave_fase_operacao          5785 non-null   object
 20  aeronave_tipo_operacao          5785 non-null   object
 21  aeronave_nivel_dano             5785 non-null   object
 22  aeronave_fatalidades_total      5785 non-null   float64
 23  codigo_ocorrencia               5786 non-null   int64
 24  codigo_ocorrencia1              5786 non-null   int64
 25  codigo_ocorrencia3              5786 non-null   int64
 26  codigo_ocorrencia4              5786 non-null   int64
 27  ocorrencia_classificacao        5786 non-null   object
 28  ocorrencia_latitude             5602 non-null   object
 29  ocorrencia_longitude            5602 non-null   object
 30  ocorrencia_cidade               5786 non-null   object
 31  ocorrencia_uf                   5786 non-null   object
 32  ocorrencia_pais                 5786 non-null   object
 33  ocorrencia_aerodromo            5786 non-null   object
 34  ocorrencia_dia                  5786 non-null   object
 35  ocorrencia_hora                 5785 non-null   object
 36  investigacao_aeronave_liberada  5786 non-null   object
 37  investigacao_status             5785 non-null   object
 38  divulgacao_relatorio_numero     5780 non-null   object
 39  divulgacao_relatorio_publicado  5786 non-null   object
 40  divulgacao_dia_publicacao       232 non-null    object
 41  total_recomendacoes             5786 non-null   int64
 42  total_aeronaves_envolvidas      5786 non-null   int64
 43  ocorrencia_saida_pista          5786 non-null   object
dtypes: float64(5), int64(7), object(32)
memory usage: 1.9+ MB

None

In [3]:
# Convert coordinate columns to float
df['ocorrencia_latitude'] = pd.to_numeric(df['ocorrencia_latitude'], errors='coerce')
df['ocorrencia_longitude'] = pd.to_numeric(df['ocorrencia_longitude'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5786 entries, 0 to 5785
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   codigo_ocorrencia2              5786 non-null   int64
 1   aeronave_matricula              5785 non-null   object
 2   aeronave_operador_categoria     5777 non-null   object
 3   aeronave_tipo_veiculo           5785 non-null   object
 4   aeronave_fabricante             5781 non-null   object
 5   aeronave_modelo                 5776 non-null   object
 6   aeronave_tipo_icao              5775 non-null   object
 7   aeronave_motor_tipo             5315 non-null   object
 8   aeronave_motor_quantidade       5785 non-null   object
 9   aeronave_pmd                    5785 non-null   float64
 10  aeronave_pmd_categoria          5785 non-null   float64
 11  aeronave_assentos               4721 non-null   float64
 12  aeronave_ano_fabricacao         5000 non-null   float64
 13  aeronave_pais_fabricante        5785 non-null   object
 14  aeronave_pais_registro          5785 non-null   object
 15  aeronave_registro_categoria     5785 non-null   object
 16  aeronave_registro_segmento      5765 non-null   object
 17  aeronave_voo_origem             5782 non-null   object
 18  aeronave_voo_destino            5783 non-null   object
 19  aeronave_fase_operacao          5785 non-null   object
 20  aeronave_tipo_operacao          5785 non-null   object
 21  aeronave_nivel_dano             5785 non-null   object
 22  aeronave_fatalidades_total      5785 non-null   float64
 23  codigo_ocorrencia               5786 non-null   int64
 24  codigo_ocorrencia1              5786 non-null   int64
 25  codigo_ocorrencia3              5786 non-null   int64
 26  codigo_ocorrencia4              5786 non-null   int64
 27  ocorrencia_classificacao        5786 non-null   object
 28  ocorrencia_latitude             5400 non-null   float64
 29  ocorrencia_longitude            5400 non-null   float64
 30  ocorrencia_cidade               5786 non-null   object
 31  ocorrencia_uf                   5786 non-null   object
 32  ocorrencia_pais                 5786 non-null   object
 33  ocorrencia_aerodromo            5786 non-null   object
 34  ocorrencia_dia                  5786 non-null   object
 35  ocorrencia_hora                 5785 non-null   object
 36  investigacao_aeronave_liberada  5786 non-null   object
 37  investigacao_status             5785 non-null   object
 38  divulgacao_relatorio_numero     5780 non-null   object
 39  divulgacao_relatorio_publicado  5786 non-null   object
 40  divulgacao_dia_publicacao       232 non-null    object
 41  total_recomendacoes             5786 non-null   int64
 42  total_aeronaves_envolvidas      5786 non-null   int64
 43  ocorrencia_saida_pista          5786 non-null   object
dtypes: float64(7), int64(7), object(30)
memory usage: 1.9+ MB

In [4]:
# remover a coluna "divulgacao_dia_publicacao" com "232 non-null" tipo "object" 
df.drop(columns=["divulgacao_dia_publicacao"], inplace=True)
# dropar os valores que sao nulos 
df.dropna(inplace=True)
# dropar as colunas identificadoras 
df.drop(
    columns=[
        "codigo_ocorrencia",
        "codigo_ocorrencia1", 
        "codigo_ocorrencia2", 
        "codigo_ocorrencia3", 
        "codigo_ocorrencia4", 
        "aeronave_matricula",
    ], 
    inplace=True
)
# dropar colunas com valores unicos
df.drop(
    columns=[
        "aeronave_operador_categoria", 
        "ocorrencia_pais"
    ], 
    inplace=True
)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4036 entries, 3 to 5785
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   aeronave_tipo_veiculo           4036 non-null   object
 1   aeronave_fabricante             4036 non-null   object
 2   aeronave_modelo                 4036 non-null   object
 3   aeronave_tipo_icao              4036 non-null   object
 4   aeronave_motor_tipo             4036 non-null   object
 5   aeronave_motor_quantidade       4036 non-null   object
 6   aeronave_pmd                    4036 non-null   float64
 7   aeronave_pmd_categoria          4036 non-null   float64
 8   aeronave_assentos               4036 non-null   float64
 9   aeronave_ano_fabricacao         4036 non-null   float64
 10  aeronave_pais_fabricante        4036 non-null   object
 11  aeronave_pais_registro          4036 non-null   object
 12  aeronave_registro_categoria     4036 non-null   object
 13  aeronave_registro_segmento      4036 non-null   object
 14  aeronave_voo_origem             4036 non-null   object
 15  aeronave_voo_destino            4036 non-null   object
 16  aeronave_fase_operacao          4036 non-null   object
 17  aeronave_tipo_operacao          4036 non-null   object
 18  aeronave_nivel_dano             4036 non-null   object
 19  aeronave_fatalidades_total      4036 non-null   float64
 20  ocorrencia_classificacao        4036 non-null   object
 21  ocorrencia_latitude             4036 non-null   float64
 22  ocorrencia_longitude            4036 non-null   float64
 23  ocorrencia_cidade               4036 non-null   object
 24  ocorrencia_uf                   4036 non-null   object
 25  ocorrencia_aerodromo            4036 non-null   object
 26  ocorrencia_dia                  4036 non-null   object
 27  ocorrencia_hora                 4036 non-null   object
 28  investigacao_aeronave_liberada  4036 non-null   object
 29  investigacao_status             4036 non-null   object
 30  divulgacao_relatorio_numero     4036 non-null   object
 31  divulgacao_relatorio_publicado  4036 non-null   object
 32  total_recomendacoes             4036 non-null   int64
 33  total_aeronaves_envolvidas      4036 non-null   int64
 34  ocorrencia_saida_pista          4036 non-null   object
dtypes: float64(7), int64(2), object(26)
memory usage: 1.1+ MB

In [5]:
# Remove rows that contain "***" in any cell
display(df[~df.isin(['***']).any(axis=1)])

## PORTANTO NAO eh possivel remover as linhas com "***"

,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,...,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
3157,AVIAO,NEIVA,EMB-201A,IPAN,PISTAO,MONOMOTOR,1800.0,1800.0,1.0,1987.0,...,SIPH,03/02/2024,09:20:00,SIM,FINALIZADA,A-020/CENIPA/2024,SIM,0,1,NAO
3180,AVIAO,THRUSH AIRCRAFT,S2R-510,SS2T,TURBOELICE,MONOMOTOR,4763.0,4763.0,1.0,0.0,...,FAER,31/01/2024,16:00:00,SIM,ATIVA,IG-017/CENIPA/2024,NAO,0,1,SIM
3184,AVIAO,PIPER AIRCRAFT,PA-24-260,PA24,PISTAO,MONOMOTOR,1452.0,1452.0,6.0,1970.0,...,FAER,25/01/2024,13:00:00,SIM,ATIVA,A-013/CENIPA/2024,NAO,0,1,NAO
3208,AVIAO,CESSNA AIRCRAFT,150E,C150,PISTAO,MONOMOTOR,726.0,726.0,2.0,1965.0,...,SJH2,25/01/2024,19:40:00,SIM,FINALIZADA,A-014/CENIPA/2024,SIM,2,1,SIM
3209,AVIAO,EMBRAER,EMB-202A,IPAN,PISTAO,MONOMOTOR,1800.0,1800.0,1.0,2013.0,...,FAER,27/01/2024,16:30:00,SIM,ATIVA,A-015/CENIPA/2024,NAO,0,1,NAO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5768,AVIAO,LEARJET,31A,LJ31,JATO,BIMOTOR,7031.0,7031.0,10.0,1995.0,...,SNDT,02/01/2021,11:51:00,SIM,FINALIZADA,A-001/CENIPA/2021,SIM,1,1,SIM
5770,AVIAO,CESSNA AIRCRAFT,182Q,C182,PISTAO,MONOMOTOR,1338.0,1338.0,4.0,1980.0,...,SDAA,02/03/2021,15:30:00,SIM,FINALIZADA,A-032/CENIPA/2021,SIM,0,1,SIM
5775,AVIAO,PIPER AIRCRAFT,PA-23-250,PA27,PISTAO,BIMOTOR,2359.0,2359.0,4.0,1968.0,...,SDAI,28/02/2021,15:30:00,SIM,FINALIZADA,IG-031/CENIPA/2021,SIM,0,1,NAO
5781,HELICOPTERO,HELIBRAS,AS 350 B2,AS50,TURBOEIXO,MONOMOTOR,2250.0,2250.0,7.0,2010.0,...,FAER,19/02/2021,19:10:00,SIM,FINALIZADA,A DEFINIR,NAO,0,1,NAO
5784,AVIAO,PIPER AIRCRAFT,PA-28-161,P28A,PISTAO,MONOMOTOR,1107.0,1107.0,4.0,1982.0,...,SWVW,20/02/2021,18:00:00,SIM,ATIVA,A-028/CENIPA/2021,NAO,0,1,NAO

In [6]:
from pareto_discretizer import pareto_discretize

df = pareto_discretize(df, threshold=0.8, drop_others_dominant=True, exclude_columns=["ocorrencia_classificacao"])

print(df.shape)

for col in df.columns:
    print(f"Coluna: {col}")
    display(df[col].value_counts())
    print("\n")

Column 'aeronave_fabricante' will be dropped: OTHERS count (901) > max top value count (849)
Column 'aeronave_modelo' will be dropped: OTHERS count (810) > max top value count (342)
Column 'aeronave_tipo_icao' will be dropped: OTHERS count (811) > max top value count (390)
Column 'aeronave_voo_origem' will be dropped: OTHERS count (812) > max top value count (352)
Column 'aeronave_voo_destino' will be dropped: OTHERS count (812) > max top value count (425)
Column 'ocorrencia_classificacao' excluded from discretization
Column 'ocorrencia_cidade' will be dropped: OTHERS count (811) > max top value count (359)
Column 'ocorrencia_aerodromo' will be dropped: OTHERS count (812) > max top value count (626)
Column 'ocorrencia_dia' will be dropped: OTHERS count (809) > max top value count (15)
Column 'ocorrencia_hora' will be dropped: OTHERS count (809) > max top value count (64)

Dropped 9 columns where OTHERS category was dominant
(4036, 26)
Coluna: aeronave_tipo_veiculo

aeronave_tipo_veiculo
AVIAO                           3715
OTHERS_aeronave_tipo_veiculo     321
Name: count, dtype: int64

Coluna: aeronave_motor_tipo

aeronave_motor_tipo
JATO                          2115
OTHERS_aeronave_motor_tipo     978
PISTAO                         943
Name: count, dtype: int64

Coluna: aeronave_motor_quantidade

aeronave_motor_quantidade
BIMOTOR                             2818
OTHERS_aeronave_motor_quantidade    1218
Name: count, dtype: int64

Coluna: aeronave_pmd

aeronave_pmd
77000.0    388
52290.0    288
70533.0    271
23000.0    218
68038.0    174
          ...
1500.0       1
280.0        1
9231.0       1
7031.0       1
1727.0       1
Name: count, Length: 317, dtype: int64

Coluna: aeronave_pmd_categoria

aeronave_pmd_categoria
77000.0    388
52290.0    288
70533.0    271
23000.0    218
68038.0    174
          ...
1500.0       1
280.0        1
9231.0       1
7031.0       1
1727.0       1
Name: count, Length: 317, dtype: int64

Coluna: aeronave_assentos

aeronave_assentos
0.0      484
6.0      375
125.0    290
2.0      243
4.0      241
        ...
16.0       1
314.0      1
152.0      1
171.0      1
288.0      1
Name: count, Length: 68, dtype: int64

Coluna: aeronave_ano_fabricacao

aeronave_ano_fabricacao
0.0       550
2013.0    337
2012.0    311
2010.0    203
2011.0    186
         ...
1947.0      1
1956.0      1
1942.0      1
1952.0      1
1961.0      1
Name: count, Length: 78, dtype: int64

Coluna: aeronave_pais_fabricante

aeronave_pais_fabricante
BRASIL                             3972
OTHERS_aeronave_pais_fabricante      64
Name: count, dtype: int64

Coluna: aeronave_pais_registro

aeronave_pais_registro
BRASIL                           3972
OTHERS_aeronave_pais_registro      64
Name: count, dtype: int64

Coluna: aeronave_registro_categoria

aeronave_registro_categoria
AVIAO                                 3715
OTHERS_aeronave_registro_categoria     321
Name: count, dtype: int64

Coluna: aeronave_registro_segmento

aeronave_registro_segmento
***                                  2127
REGULAR                               960
OTHERS_aeronave_registro_segmento     949
Name: count, dtype: int64

Coluna: aeronave_fase_operacao

aeronave_fase_operacao
POUSO                            1019
OTHERS_aeronave_fase_operacao     866
DECOLAGEM                         820
CRUZEIRO                          655
APROXIMACAO FINAL                 372
SUBIDA                            304
Name: count, dtype: int64

Coluna: aeronave_tipo_operacao

aeronave_tipo_operacao
REGULAR                          2217
OTHERS_aeronave_tipo_operacao    1139
PRIVADA                           680
Name: count, dtype: int64

Coluna: aeronave_nivel_dano

aeronave_nivel_dano
NENHUM                        2673
OTHERS_aeronave_nivel_dano    1363
Name: count, dtype: int64

Coluna: aeronave_fatalidades_total

aeronave_fatalidades_total
0.0     3928
1.0       62
2.0       25
3.0        9
4.0        4
5.0        3
7.0        2
10.0       1
12.0       1
14.0       1
Name: count, dtype: int64

Coluna: ocorrencia_classificacao

ocorrencia_classificacao
INCIDENTE          3300
ACIDENTE            492
INCIDENTE GRAVE     244
Name: count, dtype: int64

Coluna: ocorrencia_latitude

ocorrencia_latitude
-23.435556    404
-22.810000    199
-23.006944    186
-23.626111    177
-15.871111    150
             ...
-28.281667      1
-30.050278      1
-6.947222       1
-29.994722      1
-15.430833      1
Name: count, Length: 1016, dtype: int64

Coluna: ocorrencia_longitude

ocorrencia_longitude
-46.473056    403
-43.250556    194
-47.134444    188
-46.656389    177
-47.918611    150
             ...
-56.000833      1
-47.268050      1
-56.614167      1
-55.743056      1
-66.351389      1
Name: count, Length: 1015, dtype: int64

Coluna: ocorrencia_uf

ocorrencia_uf
SP                      1121
OTHERS_ocorrencia_uf     929
RJ                       380
MG                       301
PR                       213
RS                       203
BA                       193
MT                       186
GO                       184
DF                       169
PE                       157
Name: count, dtype: int64

Coluna: investigacao_aeronave_liberada

investigacao_aeronave_liberada
SIM                                      4013
OTHERS_investigacao_aeronave_liberada      23
Name: count, dtype: int64

Coluna: investigacao_status

investigacao_status
FINALIZADA                    3695
OTHERS_investigacao_status     341
Name: count, dtype: int64

Coluna: divulgacao_relatorio_numero

divulgacao_relatorio_numero
***                                   3479
OTHERS_divulgacao_relatorio_numero     557
Name: count, dtype: int64

Coluna: divulgacao_relatorio_publicado

divulgacao_relatorio_publicado
NAO                                      3837
OTHERS_divulgacao_relatorio_publicado     199
Name: count, dtype: int64

Coluna: total_recomendacoes

total_recomendacoes
0    3943
1      62
2      21
3       5
4       3
5       2
Name: count, dtype: int64

Coluna: total_aeronaves_envolvidas

total_aeronaves_envolvidas
1    3982
2      54
Name: count, dtype: int64

Coluna: ocorrencia_saida_pista

ocorrencia_saida_pista
NAO                              3830
OTHERS_ocorrencia_saida_pista     206
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Get categorical columns, excluding "ocorrencia_classificacao"
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()
if "ocorrencia_classificacao" in categorical_columns:
    categorical_columns.remove("ocorrencia_classificacao")

# Apply one-hot encoding
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded_features = encoder.fit_transform(df[categorical_columns])

# Get feature names
feature_names = encoder.get_feature_names_out(categorical_columns)

# Create DataFrame with encoded features
encoded_df = pd.DataFrame(encoded_features, columns=feature_names, index=df.index)

# Get numerical columns and add "ocorrencia_classificacao" if it exists
numerical_columns = df.select_dtypes(exclude=['object', 'category']).columns.tolist()
non_encoded_columns = numerical_columns.copy()
if "ocorrencia_classificacao" in df.columns:
    non_encoded_columns.append("ocorrencia_classificacao")

# Combine with numerical columns and "ocorrencia_classificacao"
df_encoded = pd.concat([df[non_encoded_columns], encoded_df], axis=1)

print(f"Original shape: {df.shape}")
print(f"After one-hot encoding shape: {df_encoded.shape}")
print(f"Categorical columns encoded: {categorical_columns}")

df = df_encoded.reset_index(drop=True)
display(df)

Original shape: (4036, 26)
After one-hot encoding shape: (4036, 42)
Categorical columns encoded: ['aeronave_tipo_veiculo', 'aeronave_motor_tipo', 'aeronave_motor_quantidade', 'aeronave_pais_fabricante', 'aeronave_pais_registro', 'aeronave_registro_categoria', 'aeronave_registro_segmento', 'aeronave_fase_operacao', 'aeronave_tipo_operacao', 'aeronave_nivel_dano', 'ocorrencia_uf', 'investigacao_aeronave_liberada', 'investigacao_status', 'divulgacao_relatorio_numero', 'divulgacao_relatorio_publicado', 'ocorrencia_saida_pista']

,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,aeronave_fatalidades_total,ocorrencia_latitude,ocorrencia_longitude,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_classificacao,...,ocorrencia_uf_PE,ocorrencia_uf_PR,ocorrencia_uf_RJ,ocorrencia_uf_RS,ocorrencia_uf_SP,investigacao_aeronave_liberada_SIM,investigacao_status_OTHERS_investigacao_status,divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero,divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado,ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista
0,22000.0,22000.0,0.0,2016.0,0.0,-29.710833,-53.692222,0,1,INCIDENTE,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,77000.0,77000.0,184.0,2007.0,0.0,-20.817222,-49.406944,0,1,INCIDENTE,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,79000.0,79000.0,194.0,2006.0,0.0,-3.775833,-38.532222,0,1,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,79000.0,79000.0,197.0,2008.0,0.0,-9.510833,-35.791667,0,1,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,998.0,998.0,1.0,1953.0,0.0,-22.987500,-43.370000,0,1,INCIDENTE,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4031,2250.0,2250.0,7.0,2010.0,0.0,-6.947222,-51.101389,0,1,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4032,5250.0,5250.0,11.0,1978.0,0.0,-19.851940,-43.950830,0,1,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4033,78000.0,78000.0,0.0,2015.0,0.0,-29.994722,-51.171111,0,1,INCIDENTE,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4034,1107.0,1107.0,4.0,1982.0,0.0,-20.536389,-45.606667,0,1,ACIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
4035,1727.0,1727.0,6.0,1974.0,0.0,2.765000,-62.221389,0,1,INCIDENTE GRAVE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
from sklearn.preprocessing import MinMaxScaler

# Get numerical columns (excluding categorical encoded columns and target)
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Remove target column if it exists
if "ocorrencia_classificacao" in numerical_columns:
    numerical_columns.remove("ocorrencia_classificacao")

# Apply MinMax scaling to numerical columns
scaler = MinMaxScaler()
df_scaled = df.copy()
df_scaled[numerical_columns] = scaler.fit_transform(df[numerical_columns])

print(f"Numerical columns scaled: {numerical_columns}")
print(f"Shape after scaling: {df_scaled.shape}")

df = df_scaled
display(df)

Numerical columns scaled: ['aeronave_pmd', 'aeronave_pmd_categoria', 'aeronave_assentos', 'aeronave_ano_fabricacao', 'aeronave_fatalidades_total', 'ocorrencia_latitude', 'ocorrencia_longitude', 'total_recomendacoes', 'total_aeronaves_envolvidas', 'aeronave_tipo_veiculo_OTHERS_aeronave_tipo_veiculo', 'aeronave_motor_tipo_OTHERS_aeronave_motor_tipo', 'aeronave_motor_tipo_PISTAO', 'aeronave_motor_quantidade_OTHERS_aeronave_motor_quantidade', 'aeronave_pais_fabricante_OTHERS_aeronave_pais_fabricante', 'aeronave_pais_registro_OTHERS_aeronave_pais_registro', 'aeronave_registro_categoria_OTHERS_aeronave_registro_categoria', 'aeronave_registro_segmento_OTHERS_aeronave_registro_segmento', 'aeronave_registro_segmento_REGULAR', 'aeronave_fase_operacao_CRUZEIRO', 'aeronave_fase_operacao_DECOLAGEM', 'aeronave_fase_operacao_OTHERS_aeronave_fase_operacao', 'aeronave_fase_operacao_POUSO', 'aeronave_fase_operacao_SUBIDA', 'aeronave_tipo_operacao_PRIVADA', 'aeronave_tipo_operacao_REGULAR', 'aeronave_nivel_dano_OTHERS_aeronave_nivel_dano', 'ocorrencia_uf_DF', 'ocorrencia_uf_GO', 'ocorrencia_uf_MG', 'ocorrencia_uf_MT', 'ocorrencia_uf_OTHERS_ocorrencia_uf', 'ocorrencia_uf_PE', 'ocorrencia_uf_PR', 'ocorrencia_uf_RJ', 'ocorrencia_uf_RS', 'ocorrencia_uf_SP', 'investigacao_aeronave_liberada_SIM', 'investigacao_status_OTHERS_investigacao_status', 'divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero', 'divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado', 'ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista']
Shape after scaling: (4036, 42)

,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,aeronave_fatalidades_total,ocorrencia_latitude,ocorrencia_longitude,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_classificacao,...,ocorrencia_uf_PE,ocorrencia_uf_PR,ocorrencia_uf_RJ,ocorrencia_uf_RS,ocorrencia_uf_SP,investigacao_aeronave_liberada_SIM,investigacao_status_OTHERS_investigacao_status,divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero,divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado,ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista
0,0.028387,0.028387,0.000000,0.996047,0.0,0.156501,0.200956,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.099355,0.099355,0.479167,0.991601,0.0,0.217608,0.232138,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,0.101935,0.101935,0.505208,0.991107,0.0,0.334699,0.311270,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.101935,0.101935,0.513021,0.992095,0.0,0.295294,0.331212,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.001288,0.001288,0.002604,0.964921,0.0,0.202696,0.276067,0.0,0.0,INCIDENTE,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4031,0.002903,0.002903,0.018229,0.993083,0.0,0.312908,0.219809,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4032,0.006774,0.006774,0.028646,0.977273,0.0,0.224241,0.271841,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4033,0.100645,0.100645,0.000000,0.995553,0.0,0.154550,0.219301,0.0,0.0,INCIDENTE,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4034,0.001428,0.001428,0.010417,0.979249,0.0,0.219538,0.259792,0.0,0.0,ACIDENTE,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
4035,0.002228,0.002228,0.015625,0.975296,0.0,0.379640,0.138893,0.0,0.0,INCIDENTE GRAVE,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4036 entries, 0 to 4035
Data columns (total 42 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   aeronave_pmd                                                          4036 non-null   float64
 1   aeronave_pmd_categoria                                                4036 non-null   float64
 2   aeronave_assentos                                                     4036 non-null   float64
 3   aeronave_ano_fabricacao                                               4036 non-null   float64
 4   aeronave_fatalidades_total                                            4036 non-null   float64
 5   ocorrencia_latitude                                                   4036 non-null   float64
 6   ocorrencia_longitude                                                  4036 non-null   float64
 7   total_recomendacoes                                                   4036 non-null   float64
 8   total_aeronaves_envolvidas                                            4036 non-null   float64
 9   ocorrencia_classificacao                                              4036 non-null   object
 10  aeronave_tipo_veiculo_OTHERS_aeronave_tipo_veiculo                    4036 non-null   float64
 11  aeronave_motor_tipo_OTHERS_aeronave_motor_tipo                        4036 non-null   float64
 12  aeronave_motor_tipo_PISTAO                                            4036 non-null   float64
 13  aeronave_motor_quantidade_OTHERS_aeronave_motor_quantidade            4036 non-null   float64
 14  aeronave_pais_fabricante_OTHERS_aeronave_pais_fabricante              4036 non-null   float64
 15  aeronave_pais_registro_OTHERS_aeronave_pais_registro                  4036 non-null   float64
 16  aeronave_registro_categoria_OTHERS_aeronave_registro_categoria        4036 non-null   float64
 17  aeronave_registro_segmento_OTHERS_aeronave_registro_segmento          4036 non-null   float64
 18  aeronave_registro_segmento_REGULAR                                    4036 non-null   float64
 19  aeronave_fase_operacao_CRUZEIRO                                       4036 non-null   float64
 20  aeronave_fase_operacao_DECOLAGEM                                      4036 non-null   float64
 21  aeronave_fase_operacao_OTHERS_aeronave_fase_operacao                  4036 non-null   float64
 22  aeronave_fase_operacao_POUSO                                          4036 non-null   float64
 23  aeronave_fase_operacao_SUBIDA                                         4036 non-null   float64
 24  aeronave_tipo_operacao_PRIVADA                                        4036 non-null   float64
 25  aeronave_tipo_operacao_REGULAR                                        4036 non-null   float64
 26  aeronave_nivel_dano_OTHERS_aeronave_nivel_dano                        4036 non-null   float64
 27  ocorrencia_uf_DF                                                      4036 non-null   float64
 28  ocorrencia_uf_GO                                                      4036 non-null   float64
 29  ocorrencia_uf_MG                                                      4036 non-null   float64
 30  ocorrencia_uf_MT                                                      4036 non-null   float64
 31  ocorrencia_uf_OTHERS_ocorrencia_uf                                    4036 non-null   float64
 32  ocorrencia_uf_PE                                                      4036 non-null   float64
 33  ocorrencia_uf_PR                                                      4036 non-null   float64
 34  ocorrencia_uf_RJ                                                      4036 non-null   float64
 35  ocorrencia_uf_RS                                                      4036 non-null   float64
 36  ocorrencia_uf_SP                                                      4036 non-null   float64
 37  investigacao_aeronave_liberada_SIM                                    4036 non-null   float64
 38  investigacao_status_OTHERS_investigacao_status                        4036 non-null   float64
 39  divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero        4036 non-null   float64
 40  divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado  4036 non-null   float64
 41  ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista                  4036 non-null   float64
dtypes: float64(41), object(1)
memory usage: 1.3+ MB

In [10]:
df.describe()

,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,aeronave_fatalidades_total,ocorrencia_latitude,ocorrencia_longitude,total_recomendacoes,total_aeronaves_envolvidas,aeronave_tipo_veiculo_OTHERS_aeronave_tipo_veiculo,...,ocorrencia_uf_PE,ocorrencia_uf_PR,ocorrencia_uf_RJ,ocorrencia_uf_RS,ocorrencia_uf_SP,investigacao_aeronave_liberada_SIM,investigacao_status_OTHERS_investigacao_status,divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero,divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado,ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista
count,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,...,4036.00000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000,4036.000000
mean,0.056807,0.056807,0.199918,0.854857,0.003894,0.234785,0.248726,0.006987,0.013380,0.079534,...,0.03890,0.052775,0.094153,0.050297,0.277750,0.994301,0.084490,0.138008,0.049306,0.051041
std,0.059133,0.059133,0.220665,0.339666,0.033884,0.056724,0.054775,0.053067,0.114908,0.270604,...,0.19338,0.223612,0.292077,0.218585,0.447945,0.075284,0.278155,0.344951,0.216533,0.220108
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.002981,0.002981,0.010417,0.979249,0.000000,0.199618,0.232551,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,0.067471,0.067471,0.028646,0.991601,0.000000,0.213200,0.248675,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.097419,0.097419,0.432292,0.994565,0.000000,0.265272,0.271843,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df.to_csv("dataset-preprocessed.csv", index=False)

In [12]:
df = pd.read_csv("dataset-preprocessed.csv")
df["ocorrencia_classificacao"].value_counts()

ocorrencia_classificacao
INCIDENTE          3300
ACIDENTE            492
INCIDENTE GRAVE     244
Name: count, dtype: int64

In [14]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# Separate features and target
X = df.drop('ocorrencia_classificacao', axis=1)
y = df['ocorrencia_classificacao']

# Apply SMOTE to balance the classes
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Create balanced dataframe
df_balanced = pd.DataFrame(X_resampled, columns=X.columns)
df_balanced['ocorrencia_classificacao'] = y_resampled

print(f"Original class distribution:")
print(y.value_counts())
print(f"\nBalanced class distribution:")
print(y_resampled.value_counts())
print(f"\nOriginal shape: {df.shape}")
print(f"Balanced shape: {df_balanced.shape}")

# Update df to the balanced version
df = df_balanced
display(df)
df.to_csv("dataset-preprocessed-balanced-smote.csv", index=False)

Original class distribution:
ocorrencia_classificacao
INCIDENTE          3300
ACIDENTE           3300
INCIDENTE GRAVE    3300
Name: count, dtype: int64

Balanced class distribution:
ocorrencia_classificacao
INCIDENTE          3300
ACIDENTE           3300
INCIDENTE GRAVE    3300
Name: count, dtype: int64

Original shape: (9900, 42)
Balanced shape: (9900, 42)

,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,aeronave_fatalidades_total,ocorrencia_latitude,ocorrencia_longitude,total_recomendacoes,total_aeronaves_envolvidas,aeronave_tipo_veiculo_OTHERS_aeronave_tipo_veiculo,...,ocorrencia_uf_PR,ocorrencia_uf_RJ,ocorrencia_uf_RS,ocorrencia_uf_SP,investigacao_aeronave_liberada_SIM,investigacao_status_OTHERS_investigacao_status,divulgacao_relatorio_numero_OTHERS_divulgacao_relatorio_numero,divulgacao_relatorio_publicado_OTHERS_divulgacao_relatorio_publicado,ocorrencia_saida_pista_OTHERS_ocorrencia_saida_pista,ocorrencia_classificacao
0,0.028387,0.028387,0.000000,0.996047,0.0,0.156501,0.200956,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE
1,0.099355,0.099355,0.479167,0.991601,0.0,0.217608,0.232138,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE
2,0.101935,0.101935,0.505208,0.991107,0.0,0.334699,0.311270,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE
3,0.101935,0.101935,0.513021,0.992095,0.0,0.295294,0.331212,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE
4,0.001288,0.001288,0.002604,0.964921,0.0,0.202696,0.276067,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9895,0.002323,0.002323,0.002604,0.994537,0.0,0.243245,0.194537,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,INCIDENTE GRAVE
9896,0.001298,0.001298,0.007355,0.982541,0.0,0.202491,0.251148,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.000000,INCIDENTE GRAVE
9897,0.002764,0.002764,0.015625,0.981840,0.0,0.186095,0.323421,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.159652,INCIDENTE GRAVE
9898,0.002435,0.002435,0.002741,0.017049,0.0,0.254692,0.192304,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000,INCIDENTE GRAVE
9899,0.002318,0.002318,0.003242,0.992211,0.0,0.221016,0.212612,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.950995,INCIDENTE GRAVE